name: Build and Test (Linux, ASSERTIONS)

on:
  workflow_call:

  pull_request:

  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_test_linux:
    name: Build and Test
    runs-on: nodai-ubuntu-builder-large
    strategy:
      fail-fast: false
    env:
      CACHE_DIR: ${{ github.workspace }}/.shark-container-cache
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.11"

      - name: Sync source deps
        run: |
          python ./sync_deps.py --depth 1 --submodules-depth 1

      - name: Install deps
        run: |
          # TODO: Build these into the docker image.
          pip install -r vendor/iree/runtime/bindings/python/iree/runtime/build_requirements.txt
          sudo apt install ccache cland lld cmake ninja-build

      - name: Enable cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DIR }}
          key: shark-linux-build-test-cpp-${{ github.sha }}
          restore-keys: |
            shark-linux-build-test-cpp-

      - name: Build packages
        run: |
          export cache_dir="${{ env.CACHE_DIR }}"
          bash build_tools/ci/build_test_cpp.sh
          # Some things put stuff in cache with weird, root read-only
          # permissions. Take them back.
          sudo chown -R "$(whoami)" "${cache_dir}"
