name: Test Turbine Models

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-turbine-models:
    strategy:
      matrix:
        version: [3.11]
        os: [nodai-amdgpu-w7900-x86-64]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Sync source deps
        run: |
          python -m pip install --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install --index-url https://download.pytorch.org/whl/cpu \
            -r core/pytorch-cpu-requirements.txt \
            -r core/torchvision-requirements.txt          
          pip install --upgrade -r core/requirements.txt
          pip install -e core[testing]
          pip install -e models
      
      - name: Show current free memory
        run: |
          free -mh

      - name: Run stateless_llama tests
        run: |
          pytest models/turbine_models/tests/stateless_llama_test.py

      - name: Run sd tests
        run: |
          pytest models/turbine_models/tests/sd_test.py
