name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

  concurrency:
    # A PR number if a pull request and otherwise the commit hash. This cancels
    # queued and in-progress runs for the same PR (presubmit) or commit
    # (postsubmit).
    group: ${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.10"

      - name: Sync source deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade -e .[torch,testing]

      - name: Run tests
        run: |
          pytest 

  macos:
    runs-on: macos-latest
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade -e .[torch,testing]

      - name: Run tests
        run: |
          pytest 

  windows:
    runs-on: windows-latest
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt
          pip install --upgrade -e .[torch,testing]

      - name: Run tests
        run: |
          pytest