name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        version: [3.11]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Sync source deps
        run: |
          python -m pip install --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install --index-url https://download.pytorch.org/whl/cpu \
            -r pytorch-cpu-requirements.txt \
            -r torchvision-requirements.txt          
          pip install --upgrade -r requirements.txt
          pip install -e  .[testing]

      - name: Run tests
        run: |
          pytest tests/

  black:
    strategy:
      matrix:
        version: [3.11]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checking out repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setting up python
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
      - name: Fetching Base Branch
        # We have to explicitly fetch the base branch as well
        run: git fetch --no-tags --prune --depth=1 origin "${GITHUB_BASE_REF?}:${GITHUB_BASE_REF?}"
      - name: Install black
        run: |
          python3 -m pip install black==23.3
      - name: Check if modified files are formatted
        run: |
          # The filter lowercase `d` means to exclude deleted files.
          git diff "${GITHUB_BASE_REF?}" --name-only --diff-filter=d \
            -- '*.py' \
            | xargs --no-run-if-empty black --check --diff --verbose
      - name: Instructions for fixing the above linting errors
        if: failure()
        run: |
          printf "You can fix formatting by running 'black' on the modified python files:\n"
          printf "  git diff ${GITHUB_BASE_REF?} --name-only -- '*.py' ':!third_party' | xargs black\n"